config/routes.rb
Rails.application.routes.draw do
  resources :materiels
  resources :documents
  resources :adherents
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get "home/about"
  root "home#index"
end

app/models/adherent.rb
class Adherent < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/document.rb
class Document < ApplicationRecord
end

app/models/materiel.rb
class Materiel < ApplicationRecord
end

app/controllers/adherents_controller.rb
class AdherentsController < ApplicationController
  before_action :set_adherent, only: %i[ show edit update destroy ]

  # GET /adherents or /adherents.json
  def index
    @adherents = Adherent.all
  end

  # GET /adherents/1 or /adherents/1.json
  def show
  end

  # GET /adherents/new
  def new
    @adherent = Adherent.new
  end

  # GET /adherents/1/edit
  def edit
  end

  # POST /adherents or /adherents.json
  def create
    @adherent = Adherent.new(adherent_params)

    respond_to do |format|
      if @adherent.save
        format.html { redirect_to adherent_url(@adherent), notice: "Adherent was successfully created." }
        format.json { render :show, status: :created, location: @adherent }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @adherent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adherents/1 or /adherents/1.json
  def update
    respond_to do |format|
      if @adherent.update(adherent_params)
        format.html { redirect_to adherent_url(@adherent), notice: "Adherent was successfully updated." }
        format.json { render :show, status: :ok, location: @adherent }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @adherent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adherents/1 or /adherents/1.json
  def destroy
    @adherent.destroy

    respond_to do |format|
      format.html { redirect_to adherents_url, notice: "Adherent was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adherent
      @adherent = Adherent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def adherent_params
      params.require(:adherent).permit(:id, :first_name, :last_name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: %i[ show edit update destroy ]

  # GET /documents or /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1 or /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents or /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to document_url(@document), notice: "Document was successfully created." }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1 or /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to document_url(@document), notice: "Document was successfully updated." }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1 or /documents/1.json
  def destroy
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url, notice: "Document was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def document_params
      params.require(:document).permit(:isbn, :name, :auteur, :type_doc, :is_empruntable)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/materiels_controller.rb
class MaterielsController < ApplicationController
  before_action :set_materiel, only: %i[ show edit update destroy ]

  # GET /materiels or /materiels.json
  def index
    @materiels = Materiel.all
  end

  # GET /materiels/1 or /materiels/1.json
  def show
  end

  # GET /materiels/new
  def new
    @materiel = Materiel.new
  end

  # GET /materiels/1/edit
  def edit
  end

  # POST /materiels or /materiels.json
  def create
    @materiel = Materiel.new(materiel_params)

    respond_to do |format|
      if @materiel.save
        format.html { redirect_to materiel_url(@materiel), notice: "Materiel was successfully created." }
        format.json { render :show, status: :created, location: @materiel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @materiel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materiels/1 or /materiels/1.json
  def update
    respond_to do |format|
      if @materiel.update(materiel_params)
        format.html { redirect_to materiel_url(@materiel), notice: "Materiel was successfully updated." }
        format.json { render :show, status: :ok, location: @materiel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @materiel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materiels/1 or /materiels/1.json
  def destroy
    @materiel.destroy

    respond_to do |format|
      format.html { redirect_to materiels_url, notice: "Materiel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_materiel
      @materiel = Materiel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def materiel_params
      params.require(:materiel).permit(:name, :is_empruntable, :type_mat)
    end
end

app/helpers/adherents_helper.rb
module AdherentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/materiels_helper.rb
module MaterielsHelper
end

app/views/adherents/_adherent.html.erb
<tr id="<%= dom_id adherent %>">
    <td><%= adherent.first_name %></td>
    <td><%= adherent.last_name %></td>
    <div class="container">
    <td class="row">
      <div class="">
        <button class="btn btn-info"><%= link_to "Show this adherent", adherent , class:"text-white" %></button>
      </div>
      <div class="">
        <%= button_to "Destroy this adherent", adherent, method: :delete , class:"btn btn-danger ml-2" %>
      </div>
    </td>
    </div>
</tr>

app/views/adherents/_form.html.erb
<%= form_with(model: adherent) do |form| %>
  <% if adherent.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% adherent.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div style="width: 700px ; margin: 0px auto">
  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name , class:"form-control" %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name , class:"form-control" %>
  </div>


  <div>
    <%= form.submit class:"btn btn-success mt-4" %>
  </div>
  </div>
<% end %>

app/views/adherents/edit.html.erb
<div class="container mt-4">
  <h1 class="text-center">Editing Adherents</h1>

<%= render "form", adherent: @adherent %>

<br>

<div>
  <%= link_to "Show this adherent", @adherent , class:"btn btn-secondary"%> |
  <%= link_to "Back to adherents", adherents_path, class:"btn btn-secondary" %>
</div>
</div>

app/views/adherents/index.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <h1 class="text-center">Adherents</h1>


  <div id="adherents">
  <table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">FirstName</th>
      <th scope="col">LastName</th>
      <th scope="col">Details</th>
    </tr>
  </thead>
  <tbody>
  <% @adherents.each do |adherent| %>
    <%= render adherent %>
  <% end %>
</tbody>
</table>
</div>

  <%= link_to "New adherent", new_adherent_path , class:"btn btn-success" %>

</div>

app/views/adherents/new.html.erb
<div class="container mt-4">
  <h1 class="text-center">New adherent</h1>

  <%= render "form", adherent: @adherent %>

  <br>

  <div>
    <%= link_to "Back to adherents", adherents_path , class:"btn btn-primary" %>
  </div>

</div>

app/views/adherents/show.html.erb
<div class="container mt-4">

<p style="color: green"><%= notice %></p>

<div class="jumbotron">
  <div class="d-flex justify-content-between">
    <h1 class="display-2"><%= @adherent.first_name+" "+@adherent.last_name %></h1>
    <img src="https://picsum.photos/150/150" style="border-radius: 50%" >
  </div>
  <p class="lead"></p>
  <!-- <hr class="my-4"> -->
  <p><strong>Nom : </strong><%= @adherent.last_name %></p>
  <p><strong>Prenom : </strong><%= @adherent.first_name %></p>
</div>

<div>
  <%= link_to "Edit this adherent", edit_adherent_path(@adherent) , class:"btn btn-secondary" %>
  <%= link_to "Back to adherents", adherents_path , class:"btn btn-secondary" %>
  <%= button_to "Destroy this adherent", @adherent, method: :delete , class:"btn btn-danger mt-4" %>
</div>
</div>

app/views/documents/_document.html.erb
<tr id="<%= dom_id document %>">
    <td><%= document.name %></td>
    <td><%= document.auteur %></td>
    <td><%= document.type_doc %></td>
    <td><%= document.is_empruntable %></td>
    <div class="container">
    <td class="row">
      <div class="">
        <button class="btn btn-info"><%= link_to "Show this document", document , class:"text-white" %></button>
      </div>
      <div class="">
        <%= button_to "Destroy this document", document, method: :delete , class:"btn btn-danger ml-2" %>
      </div>
    </td>
    </div>
</tr>

app/views/documents/_form.html.erb
<%= form_with(model: document) do |form| %>
  <% if document.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
        <% document.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

>

<div style="width: 700px ; margin: 0px auto">
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name ,  class:"form-control"%>
  </div>

  <div>
    <%= form.label :auteur, style: "display: block" %>
    <%= form.text_field :auteur ,  class:"form-control" %>
  </div>

  <div>
    <%= form.label :type_doc, style: "display: block" %>
    <%= form.text_field :type_doc ,  class:"form-control" %>
  </div>

  <div style="display:flex; align-items:center" class="mt-4">
    <%= form.label :is_empruntable, style: "display: block" %>
    <%= form.check_box :is_empruntable ,  class:"form-control"%>
  </div>

  <div>
    <%= form.submit class:"btn btn-success mt-4"%>
  </div>
</div>

<% end %>

app/views/documents/edit.html.erb
<div class="container mt-4">
  <h1 class="text-center">Editing Documents</h1>

<%= render "form", document: @document %>

<br>

<div>
  <%= link_to "Show this document", @document , class:"btn btn-secondary"%> |
  <%= link_to "Back to documents", documents_path, class:"btn btn-secondary" %>
</div>
</div>

app/views/documents/index.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <h1 class="text-center">Documents</h1>


  <div id="documents">
  <table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Auteur</th>
      <th scope="col">Type</th>
      <th scope="col">Empruntable</th>
      <th scope="col">Details</th>
    </tr>
  </thead>
  <tbody>
  <% @documents.each do |document| %>
    <%= render document %>
  <% end %>
</tbody>
</table>
</div>

  <%= link_to "New document", new_document_path , class:"btn btn-success" %>

</div>

app/views/documents/new.html.erb
<div class="container mt-4">
  <h1 class="text-center">New Document</h1>

  <%= render "form", document: @document %>

  <br>

  <div>
    <%= link_to "Back to documents", documents_path , class:"btn btn-primary" %>
  </div>

</div>

app/views/documents/show.html.erb
<div class="container mt-4">

<p style="color: green"><%= notice %></p>

<div class="jumbotron">
  <div class="d-flex justify-content-between">
    <h1 class="display-2"><%= @document.name %></h1>
    <img src="https://picsum.photos/150/150" style="border-radius: 50%">
  </div>
  <p class="lead"></p>
  <hr class="my-4">
  <p><strong>Type : </strong><%= @document.type_doc %></p>
  <p><strong>Auteur : </strong><%= @document.auteur %></p>
  <p><strong>Empruntable : </strong><%= @document.is_empruntable %></p>
</div>

<div>
  <%= link_to "Edit this document", edit_document_path(@document) , class:"btn btn-secondary" %>
  <%= link_to "Back to documents", documents_path , class:"btn btn-secondary" %>
  <%= button_to "Destroy this document", @document, method: :delete , class:"btn btn-danger mt-4" %>
</div>

</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<!-- <a class="navbar-brand" href="/">Bibliotheque</a> -->
<%= link_to 'Bibliotheque' ,  root_path , class:"navbar-brand" %>

<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
<ul class="navbar-nav mr-auto">
  <!-- <li class="nav-item active">
    <!-- <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a> -->
    <%# <%= link_to 'Adherents' ,  root_path , class:"nav-link" %>
  <!-- </li> -->
  <li class="nav-item">
    <a class="nav-link" href="/documents">Documents</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/materiels">Materiels</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/adherents">Adherents</a>

  </li>

</ul>
<form class="form-inline my-2 my-lg-0">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item mr-4 active">
      <!-- <a class="nav-link" href="home/about">About</a> -->
      <%= link_to 'About' ,  home_about_path , class:"nav-link" %>

    </li>
  </ul>
  <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>
</div>
</nav>

app/views/home/about.html.erb
<div class="container mt-4">
  <div class="jumbotron">
    <h1 class="display-4">Ruby On Rails Bibliotheque</h1>
    <p class="lead">This is Ruby On Rails Tp By Professor Ait Lahcen , just Simple CRUD Functionality.</p>
    <hr class="my-4">
    <p>Supervised By Mr AitLahcen Ayoub.</p>
    <a class="btn btn-primary btn-lg" href="/" role="button">Join US</a>
  </div>
</div>

app/views/home/index.html.erb
<div class="container mt-4">
  <h1 class="text-center" style="margin-bottom : 100px!important;">Welcome To Our Library</h1>
  <div class="row mt-4">
    <div class="col-6">
      <div class="card" style="width: 25rem;">
        <img src="https://picsum.photos/150/150" style="height:210px;" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Import as CSV</h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <a href="#" class="btn btn-primary">Import Now</a>
        </div>
      </div>
    </div>
    <div class="col-6">
      <div class="card" style="width: 25rem;">
        <img src="https://picsum.photos/150/150" style="height: 210px;" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Export CSV</h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <a href="#" class="btn btn-primary">Export Now</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bibliotheque</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'home/header' %>
    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
  </body>
</html>

app/views/materiels/_form.html.erb
<%= form_with(model: materiel) do |form| %>
  <% if materiel.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(materiel.errors.count, "error") %> prohibited this materiel from being saved:</h2>

      <ul>
        <% materiel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div style="width: 700px ; margin: 0px auto">
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name ,  class:"form-control"%>
  </div>

  <div>
    <%= form.label :type_mat, style: "display: block" %>
    <%= form.text_field :type_mat ,  class:"form-control"%>
  </div>

  <div style="display:flex; align-items:center" class="mt-4">
    <%= form.label :is_empruntable, style: "display: block" %>
    <%= form.check_box :is_empruntable ,  class:"form-control"%>
  </div>



  <div>
    <%= form.submit class:"btn btn-success mt-4"%>
  </div>
  </div>
<% end %>

app/views/materiels/_materiel.html.erb
<tr id="<%= dom_id materiel %>">
    <td><%= materiel.name %></td>
    <td><%= materiel.type_mat %></td>
    <td><%= materiel.is_empruntable %></td>
    <div class="container">
    <td class="row">
      <div class="">
        <button class="btn btn-info"><%= link_to "Show this materiel", materiel , class:"text-white" %></button>
      </div>
      <div class="">
        <%= button_to "Destroy this materiel", materiel, method: :delete , class:"btn btn-danger ml-2" %>
      </div>
    </td>
    </div>
</tr>

app/views/materiels/edit.html.erb
<div class="container mt-4">
  <h1 class="text-center">Editing Materiels</h1>

<%= render "form", materiel: @materiel %>

<br>

<div>
  <%= link_to "Show this materiel", @materiel , class:"btn btn-secondary"%> |
  <%= link_to "Back to materiels", materiels_path, class:"btn btn-secondary" %>
</div>
</div>

app/views/materiels/index.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <h1 class="text-center">Materiels</h1>


  <div id="materiels">
  <table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Type</th>
      <th scope="col">Empruntable</th>
      <th scope="col">Details</th>
    </tr>
  </thead>
  <tbody>
  <% @materiels.each do |materiel| %>
    <%= render materiel %>
  <% end %>
</tbody>
</table>
</div>

  <%= link_to "New materiel", new_materiel_path , class:"btn btn-success" %>

</div>

app/views/materiels/new.html.erb
<div class="container mt-4">
  <h1 class="text-center">New Materiel</h1>

  <%= render "form", materiel: @materiel %>

  <br>

  <div>
    <%= link_to "Back to materiels", materiels_path , class:"btn btn-primary" %>
  </div>

</div>

app/views/materiels/show.html.erb
<div class="container mt-4">

<p style="color: green"><%= notice %></p>

<div class="jumbotron">
  <div class="d-flex justify-content-between">
    <h1 class="display-2"><%= @materiel.name %></h1>
    <img src="https://picsum.photos/150/150" style="border-radius: 50%" >
  </div>
  <p class="lead"></p>
  <hr class="my-4">
  <p><strong>Type : </strong><%= @materiel.type_mat %></p>
  <p><strong>Empruntable : </strong><%= @materiel.is_empruntable %></p>
</div>

<div>
  <%= link_to "Edit this materiel", edit_materiel_path(@materiel) , class:"btn btn-secondary" %>
  <%= link_to "Back to materiels", materiels_path , class:"btn btn-secondary" %>
  <%= button_to "Destroy this materiel", @materiel, method: :delete , class:"btn btn-danger mt-4" %>
</div>

</div>